version: 1.0.{build}
image:
- ubuntu1804
- Visual Studio 2015
- Visual Studio 2017
- Visual Studio 2019

for:
  -
    matrix:
      only:
        - image: ubuntu1804

    build_script:
    - sh build.sh

    artifacts:
    - path: bin
      name: GrowtopiaServerModule-Ubuntu1804

  -
    matrix:
      only:
        - image: Visual Studio 2015

    build_script:
    - build.bat

    artifacts:
    - path: bin
      name: GrowtopiaServerModule-WIN-VS15

  -
    matrix:
      only:
        - image: Visual Studio 2017

    build_script:
    - build.bat

    artifacts:
    - path: bin
      name: GrowtopiaServerModule-WIN-VS17

  -
    matrix:
      only:
        - image: Visual Studio 2019

    build_script:
    - build.bat

    artifacts:
    - path: bin
      name: GrowtopiaServerModule-WIN-VS19

deploy:
- provider: GitHub
  description: GrowtopiaServer CI Build
  auth_token:
    secure: 5OeKL0BpXE39SdxcoJ6mZH7EcELGBCnKLHavhELhYtQxuVmt9ZnQu5GzsAOh1rM+
